M48
; DRILL file {KiCad (6.0.10)} date Fri Feb 17 15:19:51 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T15:19:51-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.9393Y-3.9222
X6.0997Y-3.9836
X6.2602Y-3.9232
T2
X5.9937Y-3.4
X6.1937Y-3.4
T0
M30
